version: "2"
services:
  mongo:
    container_name: mongo
    image: jqywang/opentable-menu:database1
    # volumes:
    #   - /data/db
    ports:
      - "27017:27017"
  menus:
    container_name: menus
    restart: always
    image: jqywang/opentable-menu:menu1
    #build: /home/jqywang/Documents/HackReactor/menus 
    ports:
      - "8000"
    links:
      - mongo
    command: npm start
  photos:
    container_name: photos
    restart: always
    image: leesuehee/opentable_photos:photo1
    ports:
      - "8002"
    links:
      - mongo
    command: npm start

  reviews:
    container_name: reviews
    restart: always
    #build: /home/jqywang/Documents/HackReactor/reviews
    image: dpaikoff/hrsf89_fec:reviews1
    ports:
      - "8001"
    links:
      - mongo
    command: npm start

  proxy:
    container_name: proxy
    restart: always
    build: /home/jqywang/Documents/HackReactor/proxy-jeff
    ports:
      - "80:80"
    links:
      - menus
      - reviews